"use client";
import { wrapper } from "@/store/store";
import "./globals.css";
import { Inter } from "next/font/google";
import { setAuthState } from "@/store/authSlice";
import { PersistGate } from "redux-persist/integration/react";
import { useStore } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: { children: React.ReactNode }) {
  const store: any = useStore();
  return (
    <html lang="en">
      <body className={inter.className}>
        <PersistGate persistor={store.__persistor} loading={<div>Loading</div>}>
          {children}
        </PersistGate>
      </body>
    </html>
  );
}

export default wrapper.withRedux(RootLayout);
